const products = [
 {name:'MacBook Air M2', specs:'8GB · 256GB SSD · 13.6-inch', price:'₹84,990', store:'CompuCare', cat:'Student', tag:'In stock', img:'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=500&q=80'},
 {name:'ASUS Vivobook 15', specs:'i5 13th Gen · 16GB · 512GB', price:'₹56,490', store:'IT Solutions', cat:'Student', tag:'Student offer', offer:true, img:'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=500&q=80'},
 {name:'Lenovo LOQ 15', specs:'Ryzen 7 · RTX 4050 · 16GB', price:'₹79,990', store:'PC World', cat:'Gaming', tag:'In stock', img:'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=500&q=80'},
 {name:'HP Pavilion Plus', specs:'i5 13th Gen · 16GB · OLED', price:'₹72,999', store:'CompuCare', cat:'Business', tag:'Only 2 left', offer:true, img:'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=500&q=80'},
 {name:'Logitech MX Master 3S', specs:'Wireless · Bluetooth · USB-C', price:'₹8,495', store:'IT Solutions', cat:'Accessories', tag:'In stock', img:'https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=500&q=80'},
 {name:'Acer Nitro V', specs:'i5 13th Gen · RTX 4050 · 16GB', price:'₹74,990', store:'PC World', cat:'Gaming', tag:'In stock', img:'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=500&q=80'},
 {name:'Dell Inspiron 14', specs:'i5 13th Gen · 8GB · 512GB', price:'₹61,990', store:'CompuCare', cat:'Business', tag:'In stock', img:'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=500&q=80'},
 {name:'HP 15s', specs:'Ryzen 5 · 8GB · 512GB SSD', price:'₹48,990', store:'IT Solutions', cat:'Student', tag:'Free backpack', offer:true, img:'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=500&q=80'}
];
let selected=[], activeCat='All'; const grid=document.querySelector('#productGrid');
function drawProducts(query=''){const found=products.filter(p=>(activeCat==='All'||p.cat===activeCat)&&(`${p.name} ${p.specs} ${p.cat}`).toLowerCase().includes(query.toLowerCase()));grid.innerHTML=found.map((p,i)=>`<article class="product-card"><div class="product-image"><span class="tag ${p.offer?'offer':''}">${p.tag}</span><button class="compare-check ${selected.includes(p.name)?'selected':''}" data-name="${p.name}">✓</button><img src="${p.img}" alt="${p.name}"></div><div class="product-info"><h3>${p.name}</h3><p class="specs">${p.specs}</p><div class="price">${p.price} <small>incl. taxes</small></div><div class="seller"><span>Available at <b>${p.store}</b></span><span>⌖</span></div><button class="contact-btn" data-product="${p.name}">Contact store</button></div></article>`).join('');document.querySelector('#noResults').classList.toggle('hidden',found.length>0);bindProductActions()}
function bindProductActions(){document.querySelectorAll('.compare-check').forEach(b=>b.onclick=()=>{let n=b.dataset.name;if(selected.includes(n))selected=selected.filter(x=>x!==n);else if(selected.length<3)selected.push(n);else return alert('You can compare up to 3 products.');updateCompare();drawProducts(document.querySelector('#heroSearch').value)});document.querySelectorAll('.contact-btn').forEach(b=>b.onclick=()=>{document.querySelector('#contactName').textContent=b.dataset.product;open('contactModal')})}
function updateCompare(){document.querySelector('#compareCount').textContent=selected.length;document.querySelector('#comparison').innerHTML=selected.length?selected.map(n=>{let p=products.find(x=>x.name===n);return `<div class="comparison-item"><div><b>${p.name}</b><small>${p.specs} · ${p.store}</small></div><strong>${p.price}</strong></div>`}).join(''):'<p style="color:#718095">Choose up to three products using the circle on each card.</p>'}
function open(id){document.querySelector('#'+id).classList.remove('hidden')} function closeAll(){document.querySelectorAll('.modal').forEach(x=>x.classList.add('hidden'))}
drawProducts(); updateCompare();
document.querySelectorAll('.category').forEach(b=>b.onclick=()=>{document.querySelectorAll('.category').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeCat=b.dataset.filter;drawProducts(document.querySelector('#heroSearch').value)});
document.querySelector('#searchBtn').onclick=()=>{document.querySelector('#browse').scrollIntoView();drawProducts(document.querySelector('#heroSearch').value)};document.querySelector('#heroSearch').addEventListener('keydown',e=>{if(e.key==='Enter')document.querySelector('#searchBtn').click()});
document.querySelector('#compareButton').onclick=()=>open('compareModal');document.querySelectorAll('.close').forEach(b=>b.onclick=closeAll);document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeAll()});
// dashboard
const dashboard=document.querySelector('#dashboard');function showDash(){dashboard.classList.remove('hidden');document.body.style.overflow='hidden'}document.querySelector('#openDashboard').onclick=showDash;document.querySelector('#merchantCta').onclick=showDash;document.querySelector('#backCustomer').onclick=()=>{dashboard.classList.add('hidden');document.body.style.overflow=''};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{let tab=b.dataset.tab;document.querySelectorAll('.dash-nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));document.querySelectorAll('.dash-content').forEach(x=>x.classList.toggle('hidden',x.id!==tab));document.querySelector('#dashTitle').innerHTML=tab==='overview'?'Good morning, Prathamesh <span>👋</span>':tab==='inventory'?'Manage your inventory':'Shop profile'});
let inventory=[...products.slice(0,5)];function drawInventory(){document.querySelector('#inventoryRows').innerHTML=inventory.map((p,i)=>`<div class="inventory-row"><div class="table-product"><img src="${p.img}" alt=""><div><b>${p.name}</b><small>${p.cat}</small></div></div><span>${p.price}</span><span>${i===3?'2':i===1?'3':'8'} units</span><span class="status-pill ${i===3?'low':''}">${i===3?'Low stock':'Live'}</span><button class="row-more">⋮</button></div>`).join('')};drawInventory();document.querySelector('#addProduct').onclick=()=>open('productModal');document.querySelector('#saveProduct').onclick=()=>{let name=document.querySelector('#newName').value,price=document.querySelector('#newPrice').value,cat=document.querySelector('#newCategory').value;if(!name||!price)return alert('Please add a product name and price.');inventory.unshift({name,price,cat,img:'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=500&q=80'});drawInventory();closeAll();document.querySelector('#newName').value='';document.querySelector('#newPrice').value='';alert('Product added to your storefront.')};
